### ISSUE TITLE
AMQP Compatibility

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#104]

**Comment by DiamondJoseph** [comment]
Requirements reduced by #120 but still want to support publishing events in AMQP

**Comment by keithralphs** [comment]
@callumforrester can this be closed now as a result of #105 and #107?

**Comment by callumforrester** [comment]
Neither of those were merged

**Comment by DiamondJoseph** [comment]
Nope, we're happy to just use Stomp.
