### ISSUE TITLE
Old statuses are kept unnecessarily

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#111]
When producing `TaskEvent`s. The worker includes statuses for completed operations e.g. moving a motor between two previous points in a scan. These are not needed and significantly bloat the size of the event, causing performance issues in client software.

**Comment by callumforrester** [comment]
@keithralphs The bookkeeping is done, apparently wrong, in this class: https://github.com/DiamondLightSource/blueapi/blob/main/src/blueapi/worker/reworker.py#L194

**Comment by joeshannon** [comment]
Fixed with #203
