### ISSUE TITLE
Handle Sample related metadata in a consistent way.

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#112]
Extracting Sample metadata handling (to a wrapper annotation?) and providing a consistent API for it may prevent proliferation of multiple standards of sample metadata and will allow for file writing to be more rigidly defined.

**Comment by callumforrester** [comment]
Is this still a blueapi issue?

**Comment by DiamondJoseph** [comment]
That's an ecumenical matter. If we're committing to always getting sample information from a Sample|Metadata Service, then it's not. But how to handle ad-hoc md information about Samples?

**Comment by callumforrester** [comment]
Going to close this then if you have no objection, can re-open it if a clear use case arises
