### ISSUE TITLE
Support commands via REST API

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#120]
There are two types of interaction with the worker
1. Command/response, e.g. "tell me what plans you have?" "please run this plan"
2. Continuous updates e.g. data events, task events
We wanted to use one protocol for communication so we decided on message buses. Message buses aren't fantastic in terms of support for type 1. but the normal REST approach doesn't support type 2 at all. 

We felt that the complexity/inelegance of having both approaches outweighed the cost of dealing with command/response in message buses. From discussion, it seems that that is no longer the prevailing opinion. 
The design now:
![image](https://user-images.githubusercontent.com/29771545/232048553-5608f809-b30c-4df7-a7c9-391d2df54d80.png)

**Comment by callumforrester** [comment]
@RAYemelyanova we should use this space for discussion of the API, I am vaguely thinking something along the lines of

GET `/plans`
GET `/plans/{name}`
GET `/devices`
GET `/devices/{name}`
GET `/task`
PUT `/task`

**Comment by RAYemelyanova** [comment]
In terms of the put command, I think we should actually have two routes;

1. just puts the task onto the queue. Immediately returns.
2. blocks and waits for the task to finish. Returns with appropriate error if there is one.

I think I prefer 2 but 1 is probably still useful so, should we have both?

**Comment by RAYemelyanova** [comment]
The other option is I run some validation on a task before I queue it - what do you think of this idea?
