### ISSUE TITLE
Allow querying for status of in progress and finished tasks

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#140]
Enhancement for #135 after current capabilities moved there. @RAYemelyanova 

Worth bearing in mind #111 when it comes to a finite lifespan of past tasks to query?

**Comment by keithralphs** [comment]
Current task progress will be available to clients via the Subscriptions service over Websockets (and of course on the main message bus), but it's reasonable to have a REST version of this too. Like in https://github.com/DiamondLightSource/blueapi/issues/141 retriveal fo finsihed tasks belong in the Job Manager as BlueAPI just deals with the current task and then moves on to the next.

**Comment by keithralphs** [comment]
This is somewhat duppicated by #199

**Comment by callumforrester** [comment]
This is completely duplicated by https://github.com/DiamondLightSource/blueapi/issues/199
