### ISSUE TITLE
Allow querying for names/plans of unstarted tasks

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#141]
Seperate from #140 because I fear it eventually leads to "Allow deleting unstarted tasks", "Allow re-ordering submitted tasks", "Allow editing of unstarted tasks" and other behaviours that should not be the responsibility of this service

**Comment by callumforrester** [comment]
We should probably have an issue for that: https://github.com/DiamondLightSource/blueapi/issues/157

**Comment by keithralphs** [comment]
Ought to be of the form:

GET <base_url>/tasks?status=unstarted

**Comment by stan-dot** [comment]
I am making the assumption that unstarted means `is_pending` as currentlt the Task is 
`class TrackableTask(BlueapiBaseModel, Generic[T]):
    """
    A representation of a task that the worker recognizes
    """

    task_id: str
    task: T
    is_complete: bool = False
    is_pending: bool = True
    errors: list[str] = Field(default_factory=list)
`
