### ISSUE TITLE
Endpoint for aborting/pausing/resuming the currently running task

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#142]
All behaviours of a vanilla RunEngine, but should they be exposed in this service?

**Comment by keithralphs** [comment]
> All behaviours of a vanilla RunEngine, but should they be exposed in this service?

I would say yes, this is key functionality that all Jobs, be they manual or automated will need access to

**Comment by RAYemelyanova** [comment]
I would add, we should probably have an endpoint to query what the currently running task is - as a user, you may be waiting to run your task only to have an error saying something's already running. And maybe you want to know what it is.

**Comment by keithralphs** [comment]
T

> I would add, we should probably have an endpoint to query what the currently running task is - as a user, you may be waiting to run your task only to have an error saying something's already running. And maybe you want to know what it is.

Yes, this should be of the form:

GET <base_url>/tasks/current

and should return some sort of task description response. It might also want to support query params to filter the detail that is returned or we could add /summary (or other extensions) to the end to get a reduced set of info

**Comment by keithralphs** [comment]
The form of this API element will need some discussion as it oughtt to operate on the specific task resource - i.e. <base_url>/tasks/<task_id>, but could also be seen as a separate 'task' that is applied to the existing one, in which case you could maybe create a task of the 'modifier' type that references the original one's id as a parameter. Alternatively you could do something like:

PUT/PATCH <base_url>/tasks/<task_id> supplying the task description with a 'state' field set to the requested run state
