### ISSUE TITLE
Queryable status of worker and currently running/last running plan

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#199]
There should be REST endpoints and methods on the worker class that give access to:
* The current `WorkerState`
* The status of the last plan to be run/currently running plan

**Comment by callumforrester** [comment]
Sounds good.

I think 1 is a long-term task, I would like to make a mechanism that allows us to encode progress information inside a plan. For 2 we also have the same problem, so if you have a nicer idea it might be worth a look. For 3 I think there may be a third concern as "how well did artemis work?" is different to "how well did my plan work?".

**Comment by keithralphs** [comment]
Based on Dom's comments and to be compliant with API guidelines, the endpoint for this should probably be of the form:

GET <baseurl>/tasks/<identifier>/status

where <idenifier> could be 'current', 'last' or the task id generated and returned by the service when the task was created. This would also allow for requesting a longer history of task statuses if that were deemed useful/supported.

**Comment by keithralphs** [comment]
Further to my comment above, in the latest version of the API submitted in #231, tasks which are running or have been run on the worker are going to have URLs of the form {baseurl}/worker/tasks/{identifier} so we probably want the URL form for this to be:

GET {baseurl}/worker/tasks/{identifier}/status

with {identifier} being as specified before

**Comment by callumforrester** [comment]
Closing this as I think blueapi now supports the desired functionality.
