### ISSUE TITLE
Local container build fails with dodal git dependency

### ISSUE THREAD

**Issue by abbiemery** [DiamondLightSource/blueapi#200]
As picked up in this skeleton [issue](https://github.com/DiamondLightSource/python3-pip-skeleton/issues/127), git dependencies cause issues with container builds because the dependency gets locked into the requirements.txt with the latest hash and then gets compared to one without a hash, which it then thinks are different things and fails the `RUN pip install ${PIP_OPTIONS}` command.

I followed the work around pointed out by callum in the above issue, however this is just for the CI and doesn't help for a local build. 

There might be something else at play breaking the local builds in addition, I have not investigated.

**Comment by callumforrester** [comment]
Might be solved by #359

**Comment by stan-dot** [comment]
would we want auto closing inactive issues? ([with github actions](https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues))

I haven't experienced any build issues, devcontainer setup is very smooth 😁
@callumforrester

**Comment by callumforrester** [comment]
@abbiemery is this still an issue for you?
