### ISSUE TITLE
Test that OpenAPI Schema is unchanged

### ISSUE THREAD

**Issue by joeshannon** [DiamondLightSource/blueapi#235]
There is currently an action to generate the schema but this does not validate that it matches the schema present in the repository at
`docs/user/reference/openapi.yaml`.

It is important that these match as client libraries are generated from this file.

The check could probably be replaced with a Python test.

**Comment by stan-dot** [comment]
additionally a versioning field might be added to the schema to show breaking changes https://stackoverflow.com/questions/54691517/service-versioning-in-openapi

**Comment by stan-dot** [comment]
this job is key
https://github.com/DiamondLightSource/blueapi/actions/runs/8927707817/job/24521677000

**Comment by callumforrester** [comment]
@joeshannon What do you need that https://github.com/DiamondLightSource/blueapi/blob/main/tests/service/test_openapi.py doesn't do?

**Comment by joeshannon** [comment]
This is an old ticket that forgot to be closed I think.

**Comment by joeshannon** [comment]
Fixed by #238

**Comment by stan-dot** [comment]
https://github.com/DiamondLightSource/blueapi/pull/452#issuecomment-2093180637

I'm not sure @joeshannon
