### ISSUE TITLE
Create actions that run on merged/rebased PRs

### ISSUE THREAD

**Issue by joeshannon** [DiamondLightSource/blueapi#237]
Currently it appears that the actions run on the PR branch, as pushed.
Since branches could have an old merge-base with respect to `main`, the important checks and tests can become out of date.
We should try and run actions against a merged or rebased version of the PR to avoid this.

**Comment by stan-dot** [comment]
doing this should be easy - Dodal has this setup

**Comment by stan-dot** [comment]
maybe I'm getting something wrong, but isn't this automatic already? github already forces you to merge/rebase and then re-runs the jobs 
![image](https://github.com/DiamondLightSource/blueapi/assets/56644812/87e1780a-fd7b-479f-9a7e-f43a9ed54a10)

**Comment by joeshannon** [comment]
Yes this is the case now as we have enabled the "Require branches to be up to date before merging" branch protection rule.
If this option is not enabled then the checks run on the head of the PR before it is merged which could be out of date leading to failures when the check runs after the PR is merged.
