### ISSUE TITLE
Delete RunPlan and use just Task

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#253]
Currently, `RunPlan` extends `Task` because we expected multiple types of `Task`. Now this seems unlikely, `Task` should just become an ordinary pydantic model. It may also be useful at this point to move the logic for running a task out of `RunPlan` and into `RunEngineWorker` as polymorphism is no longer needed.

**Comment by stan-dot** [comment]
working on this as #206  needs this

**Comment by stan-dot** [comment]
running the tests to ensure correct setup. getting an error of 'integration-test' kind (?).
`File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 628, in send
    raise exception.NotConnectedException()
stomp.exception.NotConnectedException`

in `test_stomptemplate.py`
