### ISSUE TITLE
Support importing Callback modules that subscribe to the RunEngine

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#257]
Optionally: Make the current worker.events a callback in a default package of callbacks to make it optional

**Comment by callumforrester** [comment]
One way to do this that is already supported
```python
def my_plan() -> MsgGenerator:
    my_callback = MyCallback()
    my_other_callback = MyOtherCallback()

    @subs_decorator([my_callback, my_other_callback])
    def inner_plan() -> MsgGenerator:
        # actual plan logic goes here

    yield from inner_plan()
```

This could be sufficient...

**Comment by stan-dot** [comment]
@DiamondJoseph , what do you think?

**Comment by DiamondJoseph** [comment]
> @DiamondJoseph , what do you think?

The linked issue has this left in Artemis/Hyperion/mx-blueksy's remit and was a year ago. I'm happy to close and re-open when we have more concrete requirements.
