### ISSUE TITLE
Add stage to release pipeline to pin dependencies

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#271]
Allows dev to continue with latest version of dependencies and prevent us slipping further and further behind the wider world, while also providing a known working state when releasing.

**Comment by stan-dot** [comment]
@DiamondJoseph how would this look technically? a line in `pyproject.toml`?

**Comment by stan-dot** [comment]
@DiamondJoseph what's your current take on this?

**Comment by DiamondJoseph** [comment]
I haven't done any more thinking about it. Hopefully now that ophyd-async is trending towards stability it shouldn't be required now?

**Comment by DiamondJoseph** [comment]
I'd say not to focus on it right now

**Comment by stan-dot** [comment]
@DiamondJoseph have you known about [this file](https://github.com/DiamondLightSource/blueapi/blob/main/.github/workflows/_test.yml) when raising the issue? see lines 50 to 65

**Comment by DiamondJoseph** [comment]
@stan-dot This issue was raised in June 2023, that file was added to the repository 3 months ago. Causality demands that no I didn't know ;)

**Comment by stan-dot** [comment]
ok, should we close this?

**Comment by stan-dot** [comment]
looking at the base issue

> Allows dev to continue with latest version of dependencies and prevent us slipping further and further behind the wider world, while also providing a known working state when releasing.

@callumforrester do you disagree with the premise? I heard that there are divergent viewpoints design-and-workflow in regards to dependencies

**Comment by callumforrester** [comment]
@stan-dot I agree with this premise for applications, at least

**Comment by stan-dot** [comment]
ok, and this is blueapi, which is an application. Can we merge #499 now @DiamondJoseph ?

**Comment by DiamondJoseph** [comment]
@stan-dot sure, let's see how Dependabot keeps up, I'll make some time next week to have a look at its configuration
