### ISSUE TITLE
Improve documentation landing pages and tutorials

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/blueapi#279]
As a user/developer trying to use blueapi for the first time the documentation does not guide me very well.

* The landing page doesn't tell me what `blueapi` is or why I would want to use it
* The tutorials contain some info on starting it but not the context for how this fits into the bigger picture
* The developer guide has some good info at https://diamondlightsource.github.io/blueapi/main/developer/explanations/lifecycle.html but to a new user this is buried and doesn't give a good step by step of "I want to make a plan then be able to call it externally"

**Comment by callumforrester** [comment]
@DominicOram What do you think about it at the moment?

**Comment by DominicOram** [comment]
Obviously documentation is always a bit of a WIP but it's a lot better now, thanks for all your efforts!
