### ISSUE TITLE
Refactor pod and deployment annotations to allow injection from supercharts

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#286]
e.g. .Values.podLabels, for use for Auth|Auth and enabling ServiceMeshes

**Comment by stan-dot** [comment]
please make this clearer and more verbose @DiamondJoseph

**Comment by DiamondJoseph** [comment]
Deprecated by aims of not deploying as an umbrella chart anymore.

If/when we need labels on our pod for Auth we'll need to add them to this repo.
