### ISSUE TITLE
Allow fetching and installation of plan/device modules on startup

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#307]
In order to prevent the bloating of the size of the base image/complaints & possible confusion from having to have dependencies on seemingly irrelevant code, it would be beneficial if naming a module (which exists on pypi) in the config would fetch and install that module prior to attempting to get plans/devices from it. This also means that a list of such modules would only need to be maintained per-beamline, rather than per-beamline and also centrally in pyproject.toml.

**Comment by DiamondJoseph** [comment]
This would however make startup of the service slower. 

How slow compared to having to pull a larger image in the first place may be a question to explore (build time slowness not worth worrying about compared to per-restart)

**Comment by callumforrester** [comment]
This was partly covered by the introduction of a scratch area, may be solved by https://github.com/DiamondLightSource/blueapi/issues/363?

**Comment by callumforrester** [comment]
I think having a configurable scratch area (#520) solves the rest of this problem, feel free to reopen if there's something else you think needs to be covered.
