### ISSUE TITLE
Once dependencies have been released, stop excluding packages from lockfiles

### ISSUE THREAD

**Issue by rosesyrett** [DiamondLightSource/blueapi#319]
At the moment, the pyproject.toml has a lot of dependencies that actually look at branches of git repos. For pip this is a problem, because it doesn't know what version to ascribe to these packages, and when comparing them with other versions (even if they come from the same branch of the same repo) it fails. For this reason, in order to placate the container CI job on #315 , I've just modified the job that makes those lockfiles, and the one that uses them.

This is an issue to remind us that, when these dependencies have releases, we should not do it in this manner; we should get rid of the calls to '--exclude' in .github/actions/install_requirements/action.yaml and remove the extra pip install's of git repos in the 'Build runtime image' step of the container CI job.

**Comment by stan-dot** [comment]
connected to #271

**Comment by stan-dot** [comment]
@callumforrester I judge from the description of the issue that it is no longer a concern, is this right?

**Comment by callumforrester** [comment]
Agreed
