### ISSUE TITLE
Support PKCE authentication flow

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#347]
PKCE flow is the flow we want, not device flow.

Need to find out if our current AuthN solution supports it, or else wait until the Keycloak deployment is available to develop against.

**Comment by stan-dot** [comment]
PKCE stands for [Proof Key for Code Exchange](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-pkce)

**Comment by callumforrester** [comment]
We will support device flow only until web clients come along, at which point we will need to support a full OIDC flow. PKCE flow is not needed either way.
