### ISSUE TITLE
Move preprocessors to dodal

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#353]
There is currently a `preprocessors` package in blueapi which holds [plan preprocessors](https://blueskyproject.io/bluesky/plans.html#plan-preprocessors) that can be applied to all plans that blueapi runs. It doesn't really belong here, it should be an optional plugin.

The preprocessor code should live in dodal. There should be a way of optionally ingesting preprocessors on startup and applying them to all plans.

**Comment by callumforrester** [comment]
@DominicOram Opinions welcome

**Comment by DominicOram** [comment]
We don't really use `preprocessors` at the moment so I don't really have any strong opinions. I agree that code that is actually logic of what to do on the beamline (which I assume is what your `preprocessors` are) should live in `dodal`

**Comment by callumforrester** [comment]
@joeshannon and I have been looking at this. Are there any plans currently in dodal we could look at @DominicOram? In particular we're wondering where beamline-specific configuration for general plans should go (rough equivalent of GDA properties).

**Comment by callumforrester** [comment]
@DiamondJoseph correct me if I'm wrong but this is now done
