### ISSUE TITLE
Remove dependency on dls-bluesky-core

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#356]
`dls-bluesky-core` has been deprecated and its functionality moved to `dodal`

**Comment by callumforrester** [comment]
The dependency in `pyproject.toml` needs updating, as do the imports unless @DiamondJoseph has already updated them?

**Comment by callumforrester** [comment]
@DiamondJoseph please find the PR that did this and close

**Comment by DiamondJoseph** [comment]
Closed by 

https://github.com/DiamondLightSource/blueapi/pull/645
