### ISSUE TITLE
Remove example configs from repo root

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#357]
The config files in `configs/` in this repository have no purpose except as examples, this keeps confusing people so it's best to either delete them or move them into the docs. If the latter option is chosen there should still be tests to make sure they don't go out of date.

**Comment by stan-dot** [comment]
connected to #352 where imports from `ophyd` are used as demonstrations of `example_devices`.

alternatively a new repo with blueapi examples could be made

**Comment by stan-dot** [comment]
just delete, examples are already in https://gitlab.diamond.ac.uk/daq/d2acq/examples/daq-deployments

**Comment by stan-dot** [comment]
there's 1 small test that relied on the `defaults.ymal` - can it be deleted  - @callumforrester ?
