### ISSUE TITLE
Review CLI docs

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#361]
It has been suggested that our CLI docs are out of date. This issue is just a reminder to review and remedy where necessary.

**Comment by stan-dot** [comment]
to contrary - CLI is the most self-documenting thing and does not need docs beside docstrings? agile is less documentation

**Comment by stan-dot** [comment]
the time-saving thing is still to just delete. CLI relies heavily on the REST and the click library, the logic there is thin and evident.

tests are documentation

**Comment by callumforrester** [comment]
Tests are documentation for developers, we are talking about documentation for users: https://diamondlightsource.github.io/blueapi/main/how-to/run-cli.html

**Comment by stan-dot** [comment]
but here the users would be the support teams. they could read the python code, right?

**Comment by callumforrester** [comment]
Not wanting to get too far down a philosophical rabbit hole, but by that logic, libraries shouldn't have docs because "their users developers and developers can read code, right?". I can't say I agree, imagine trying to figure out how to use pydantic, say, without these: https://docs.pydantic.dev/latest/

**Comment by stan-dot** [comment]
it's an economic / praxeological, not philosophical question. 

pydantic has a very high ratio of users to developers (millions to one) and high volume of developer input to user input ( thousands of hours to one).

our use case is different - support engineers (users) are around 2 or 3 to 1 compared to the blueapi team, and also users (software support engineers) will be expected to deal with various issues in the core code.

**Comment by Tom-Willemsen** [comment]
> the time-saving thing is still to just delete

No. Time spent writing good documentation pays itself back manyfold over the course of a project.

> CLI is the most self-documenting thing

I disagree that CLIs are self-documenting. There is value in having both a tutorial-style walkthrough _and_ a detailed API reference. Imagine trying to figure out how to use `ssh` by just reading `man ssh` - it's a great technical reference for someone who already knows the basics, but there is value in tutorial-style walkthroughs too.

> the users would be the support teams. they could read the python code, right?

I use many many CLIs each day. I've never read the source code behind 99.9% of them. `blueapi` should be no different, it should be possible for both a first time user to do the basics (via a tutorial-style walkthrough) and a more advanced user to get to the detailed options (via a detailed reference) without ever reading the code.

> users (software support engineers) will be expected to deal with various issues in the core code

So make it easier for them by writing good documentation.

**Comment by stan-dot** [comment]
![image](https://github.com/DiamondLightSource/blueapi/assets/56644812/f4a70d00-7caf-4433-b49e-e5e451a91455)

this took me 3 minutes and that is just the self-documentation from the code. 

the point raised by OP was that it's difficult to keep docs up to date, not that it's difficult to make it good.

if docs are unreliable, people will checkout the code anyway. 

regardless, there is no version 1.0 that is module - loadable (#402), so breaking changes are to be expected. 
right now the project does not have too many users and developer effort is scarce - what little there is available is devoted to bugs and functionality. 

Of course for 1.0 a small and easy to maintain online guide would be good
