### ISSUE TITLE
Add CLI commands to inspect/restart the environment

### ISSUE THREAD

**Issue by joeshannon** [DiamondLightSource/blueapi#366]

**Comment by stan-dot** [comment]
what are the features of environment we want to inspect here? is it about pip environment? or beamline-specific config?

**Comment by joeshannon** [comment]
This to add cli support for the [environment](https://github.com/DiamondLightSource/blueapi/blob/7bbc94e0d61da2a4ce4de6a1285c4cc0e4ba67f2/src/blueapi/service/main.py#L86) end points. This allows the bluesky context to be reloaded without restarting the whole service which is useful if blueapi is loading plans from a "scratch" area to allow rapid development/testing.

**Comment by stan-dot** [comment]
`
@app.get("/environment", response_model=EnvironmentResponse)
def get_environment(
    handler: BlueskyHandler = Depends(get_handler),
) -> EnvironmentResponse:
    return EnvironmentResponse(initialized=handler.initialized)


@app.delete("/environment")
async def delete_environment(
    background_tasks: BackgroundTasks,
    handler: BlueskyHandler = Depends(get_handler),
):
    def restart_handler(handler: BlueskyHandler):
        handler.stop()
        handler.start()

    if handler.initialized:
        background_tasks.add_task(restart_handler, handler)
`

I see only two endpoints right now - get and delete, no 'reload'. Reading into the calls from `delete` it looks like that it is how the reload should be performed. 

would the minimal implementation user experience be of this kind: `blueapi env` and `blueapi env reload`? with some alternatives names possible ('env r') for faster reload?

**Comment by callumforrester** [comment]
You're correct, "reload" is a verb, so shouldn't be in the rest api. But the CLI can combine nouns into a verb. So your suggested UX looks good.

**Comment by stan-dot** [comment]
ok will implement that, it should be a pretty minimal addition

**Comment by stan-dot** [comment]
currently `{'initialized': True}` is as much of an inspection `main.py` allows:

`
@app.get("/environment", response_model=EnvironmentResponse)
def get_environment(
    handler: BlueskyHandler = Depends(get_handler),
) -> EnvironmentResponse:
    return EnvironmentResponse(initialized=handler.initialized)
    `

**Comment by stan-dot** [comment]
using `blueapi controller env` as that `click` command group has already the rest client in the context, hence as this env command also uses the rest client it only makes sense that it is under `command` not `main`

**Comment by stan-dot** [comment]
`  none is not an allowed value (type=type_error.none.not_allowed)` Pydantic complains. @callumforrester could you check `cli.py:114`?

**Comment by stan-dot** [comment]
thinking how to fix the test which fails now that there's the 'sleep(5) line there

**Comment by stan-dot** [comment]
testing sleep does not seem to be well-supported
https://github.com/pytest-dev/pytest/discussions/11196
