### ISSUE TITLE
Move ophyd-async connect logic to dodal

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#387]
Blueapi should be agnostic to how devices are connected, dodal should handle that.
There is currently a util module for handling connections, that should move to dodal and blueapi should just call a `connect` hook or similar

**Comment by callumforrester** [comment]
Additionally, there is duplication at work here: Dodal has its own version here: https://github.com/DiamondLightSource/dodal/blob/4cd34cfbdc9e9fc3e963a0a88db36b6a79cc463a/src/dodal/beamlines/beamline_utils.py#L48

We should have a single, consistent space for this logic that behaves in the same way everywhere to reduce ambiguity and minimize the chance of a mistake when debugging.

**Comment by stan-dot** [comment]
@coretl what do you think about this?

**Comment by coretl** [comment]
https://github.com/DiamondLightSource/dodal/issues/483 and https://github.com/DiamondLightSource/blueapi/issues/440 are relevant

**Comment by callumforrester** [comment]
This issue is stale, the logic is now in dodal and not blueapi (it was in both for a while, which we didn't notice because it is idempotent), it was removed in #461.

I will close this, discussion can continue in the issues @coretl linked
