### ISSUE TITLE
Convert all of docs to markdown

### ISSUE THREAD

**Issue by joeshannon** [DiamondLightSource/blueapi#392]
Follow on from https://github.com/DiamondLightSource/blueapi/issues/359

**Comment by stan-dot** [comment]
using this script: 
`#!/bin/bash

# Define the path to the docs directory
DOCS_DIR="./docs"

# Check if pandoc is installed
if ! command -v pandoc &> /dev/null
then
    echo "pandoc could not be found, please install it first."
    exit 1
fi

# Convert all .rst files in the docs directory to .md
find "$DOCS_DIR" -type f -name "*.rst" | while read file; do
    # Define the output filename by replacing the extension
    output_file="${file%.rst}.md"
    
    # Use pandoc to convert the file
    pandoc "$file" -s -o "$output_file"
    
       # Remove the original .rst file after conversion
    rm "$file"

    # Optionally, echo the output file name
    echo "Converted and removed '$file', created '$output_file'"
done

echo "Conversion complete."
`

**Comment by stan-dot** [comment]
possibly images need a different handling

**Comment by stan-dot** [comment]
did markdown import for images
