### ISSUE TITLE
Remove Startup Script

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#399]
The [startup script](https://github.com/DiamondLightSource/blueapi/blob/main/container-startup.sh) performs an editable `pip install` of every directory in scratch and then starts blueapi. This was needed because the `pip install` needed to happen before the process containing the run engine started. Following #343, the RE is run in a subprocess, which means the pip install can be performed from the main process rather than a script.

We've seen some reliability issues with the script which this may improve, but the primary business need is paving the way to auto-reloading things in scratch without needing to restart the entire blueapi process (just the subprocess).

Tagging @joeshannon in case he can think of any other issues.

**Comment by stan-dot** [comment]
is this just waiting for #365  then?

**Comment by callumforrester** [comment]
@stan-dot no, this can be done at any time, documentation would be nice but is not blocking
