### ISSUE TITLE
Stomp Tests Timeout Forever

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#401]
If I run the stomp tests without a valid message bus running, they should fail within the 10 second timeout (they usually fail earlier when disconnection occurs). They currently hang forever, this behaviour seems to have been present since #345 so probably has something to do with the fact that we are now logging exceptions rather than raising them. This would be unfortunate as it means our solution that made the CLI easier to use makes the tests harder to use.

This ticket is therefore to come up with a solution to #220 that also works for this.

**Comment by stan-dot** [comment]
this annoyed me just today. one time too many. will fix

**Comment by stan-dot** [comment]
got some work for this by mistake into #441

**Comment by stan-dot** [comment]
should we have some `pytest.mark` to NOT run those tests at all in the CI unit test setup? @callumforrester

**Comment by callumforrester** [comment]
They should _always_ run in CI, and I haven't seen any problems with them in CI, have you?

I see the problem when running locally. We already have a `pytest.mark` to make them opt-out. We could change it to make them opt-in? Or, like dodal does, include the opt-out in the `tox` command

**Comment by stan-dot** [comment]
nevermind, I missed that mark at first.

**Comment by stan-dot** [comment]
todo: should add here in a new PR changes that were explored in #364  PR

**Comment by stan-dot** [comment]
one possible course of action is to mock - change this in the tests: `        time.sleep(self._reconnect_policy.initial_delay)` so that we don't need to wait

**Comment by stan-dot** [comment]
running `pytest -m"stomp"`

**Comment by stan-dot** [comment]
what I see is that the test fails but then the debugger keeps running

**Comment by stan-dot** [comment]
going with the debugginer the culprit is here 
![image](https://github.com/DiamondLightSource/blueapi/assets/56644812/c7d2a08c-cc41-42fe-be1e-ff25426adece)

**Comment by stan-dot** [comment]
solved with #491
