### ISSUE TITLE
Cannot run plans without a message bus (server)

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#426]
Blueapi can start up without connecting to a message bus but fails to run any plans because the message bus is currently interconnected with the worker. 

## To Reproduce

Terminal 1
```shell
# start blueapi server
blueapi serve
```

Terminal 2
```shell
# Simple plan
blueapi controller run sleep '{"time": 5}'

# More complex plan
blueapi controller run count '{"detectors": ["det"]}'
```

## Possible solution
Make the message template an optional part of the handler and make it `None` if connection fails. Perform None-checks on it wherever it is used. Hopefully if its type is declared as optional in all the right places mypy should point out all the usages where it is assumed to be present.
 

## Acceptance Criteria
- Can run the demo set of plans without connecting blueapi to a message bus
- Tests to prove that the message bus usages are guarded

**Comment by ZohebShaikh** [comment]
In the Terminal 2 the example is given for the CLI which should raise exceptions when trying to run https://github.com/DiamondLightSource/blueapi/issues/427#issuecomment-2078755742
The blueapi server can run plans without a message bus and there are already tests to check it in the test_rest_api.py it uses a `handler = Handler(context=context, messaging_template=MagicMock())`
MagiMock which will run with a None as well

There are tests added to check if the message bus use is guarded
