### ISSUE TITLE
Cannot run plans without a message bus (client)

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#427]
Relates to #426, the blueapi CLI listens to updates from the server via the message bus so it throws an error if you try to use blueapi without a bus being present. 

## To Reproduce

Terminal 1
```shell
# start blueapi server
blueapi serve
```

Terminal 2
```shell
# Simple plan
blueapi controller run sleep '{"time": 5}'

# More complex plan
blueapi controller run count '{"detectors": ["det"]}'
```

## Possible solution
The CLI does have a message bus-free mode that can be enabled with a flag, we should also enable it if the connection fails and print a warning to the user. In this case the CLI does not block until the plan completes but expects the user to run further commands to poll the server. The warning message should make this clear. 

## Acceptance Criteria
- Can run plans via the CLI without a message bus without getting stomp errors
- Appropriate changes to CLI tests

**Comment by callumforrester** [comment]
> The CLI does have a message bus-free mode that can be enabled with a flag

As it turns out I was misremembering. So will accept the CLI raising early if it can't connect to the bus

**Comment by ZohebShaikh** [comment]
The use of message bus is guarded and there are tests added to check this for the CLI .
The changes mentioned are in this PR: https://github.com/DiamondLightSource/blueapi/pull/433
