### ISSUE TITLE
Deprecate task.dict()

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#435]
> The method "dict" in class "BaseModel" is deprecated
> The `dict` method is deprecated; use `model_dump` instead.Pylance

chante the data=task.dict() to data=task.model_dump()

**Comment by callumforrester** [comment]
No need to deprecate use in blueapi, can just be a change as it doesn't break any APIs

**Comment by callumforrester** [comment]
@stan-dot can this be part of #449?
