### ISSUE TITLE
Use `StatefulSet` rather than `Deployment` in helm chart

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#458]
As a support engineer I would like blueapi to be handled like a stateful application (which it is) on kubernetes so that it behaves in a predictable manner without two coexisting instances during the reconciliation phase.

@gilesknap has found success in using the kubernetes [`StatefulSet`](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) to manage IOCs, as opposed to [`Deployment`](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). It instructs kubernetes to manage a process as though it is stateful (i.e. that one instance may not behave exactly the same as another, depending on what has already happened to it), preventing overlapping instances.

## Acceptance Criteria
- `Deployment` removed from helm chart
- `StatefulSet` in place instead

**Comment by callumforrester** [comment]
Labelling this as a bug as it causes unexpected behaviour. For example when running on host network it may not be able to restart as both the terminating pod and the starting pod are fighting over the same port on the host machine.

**Comment by gilesknap** [comment]
Just came here to say that this is a pretty easy change to make. For the most part

sed s/Deployment/Statefulset/ -i my-helm-chart.yaml

is all you need.
