### ISSUE TITLE
Containerised blueapi should write files to mounted dir with group 

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#460]
blueapi container running on the k8s cluster, as part of installing files in its blueapi scratch dir generated py_cache folders without group ownership, meaning they could not be easily deleted.

**Comment by callumforrester** [comment]
Alternatively, is there a way to stop it generating `__pycache__` files? It currently does a `pip install -e`, which is not necessary as it does it again on restart anyway.

**Comment by stan-dot** [comment]
```
drwxrwsrwx+  4 xma12127           dls_dasc 4.0K Sep 20 09:37 .
drwxrwsr-x+  3 xma12127           dls_dasc 4.0K Sep 17 15:06 ..
drwxrwxr-x+ 11 k8s-b01-1-beamline dls_dasc 4.0K Sep 20 10:45 ViSR
drwxrwxr-x+ 10 k8s-b01-1-beamline dls_dasc 4.0K Sep 24 11:13 dodal
```

I don't think it's a problem at this point in time

**Comment by callumforrester** [comment]
@stan-dot I think it is now less of a problem, but the `s` flag in `.` in your output is the magic that makes it work, scratch directories without that can still have problems, this needs further investigation.

**Comment by stan-dot** [comment]
this would be redundant if we get #662  or #363  done

**Comment by callumforrester** [comment]
I have consolidated a few issues, including ones documented here into https://github.com/DiamondLightSource/blueapi/issues/747, closing as duplicate
