### ISSUE TITLE
Delete the 'worker' abstract class

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#479]
We have only 1 class implementing this and now every change needs to happen twice. We pay the costs of this OOP pattern and do not get the benefits.

**Comment by stan-dot** [comment]
connected to #363  and #504

**Comment by callumforrester** [comment]
I realise it has been discussed offline but would be good if you could include a justification here, thanks

**Comment by stan-dot** [comment]
it was a month ago, so the details might be less accurate but I'll try
