### ISSUE TITLE
Modularize models and handlers 

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#486]
![image](https://github.com/DiamondLightSource/blueapi/assets/56644812/bf207ef4-af8f-4ebd-93cb-8e9054c493a4)

split handler into multiple different classes, DeviceHandler, TasksHandler, etc

Optionally also to the router like this: 

`from fastapi import FastAPI
from tasks.router import router as tasks_router
from devices.router import router as devices_router
from plans.router import router as plans_router

app = FastAPI()

app.include_router(tasks_router, prefix="/api")
app.include_router(devices_router, prefix="/api")
app.include_router(plans_router, prefix="/api")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
`

**Comment by callumforrester** [comment]
Duplicate of #434
