### ISSUE TITLE
Failure to reload the subprocess gets blueapi into an unrecoverable state

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#512]
To reproduce:
1. Run blueapi against a scratch area
2. Edit the code to introduce a fatal bug (e.g. a syntax error)
3. Reload
4. Fix the bug
5. Try to reload again

**Comment by joeshannon** [comment]
The cause of this is that in the endpoint for environment DELETE, the context is only restarted if there exists an initialized context already. The intention was to prevent repeated calls to the endpoint from "stacking up" however on reflection this might not really have been addressed.

When there is a failure the initialized property on SubprocessHandler is never set to true.

We should add an error property to the environment context to allow it to restart if there are errors too.

It can be added to the environment entity.

**Comment by stan-dot** [comment]
I think with #504 we wouldn't have this kind of issue
