### ISSUE TITLE
Test JINJA auto-generated GUIs

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#516]
Would approximate something like [this](https://github.com/renceInbox/fastapi-todo). Much more friendly to Python developers, as we already use Go-template syntax inside Helm charts and Python. Using React brings problems

**Comment by stan-dot** [comment]
should this be closed in favor of the react setup (#536 ) ? 

@callumforrester @keithralphs ?

**Comment by callumforrester** [comment]
Yes, thanks!
