### ISSUE TITLE
Investigate splitting into many packages with a shared Dockerfile-base

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#562]

**Comment by stan-dot** [comment]
what is interesting and necessary to get a clear answer on is how are plans defined? they cannot be serialized

**Comment by stan-dot** [comment]
the list of necessary changes is in the `todo.md` file. This awaits the #363

**Comment by stan-dot** [comment]
@callumforrester this is required for the scenario where the rest api to run in the central cluster while the worker runs on the beamline. do you have any preferences wrt implementation?

**Comment by callumforrester** [comment]
Will do, I suggest we raise a separate issue about image size optimisation when we decide that is a problem
