### ISSUE TITLE
Configure CodeQL and sonarcloud

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#595]
following the outline in the suggestion to add those tools to the copier template - it should be tested first 
https://github.com/DiamondLightSource/python-copier-template/issues/180

a link to the current report could be provided in the README

**Comment by callumforrester** [comment]
@stan-dot strange, you were able to request it for other repos, correct?

**Comment by stan-dot** [comment]
it might be complicated

**Comment by stan-dot** [comment]
waiting for @callumforrester 's reponse

**Comment by callumforrester** [comment]
Approved

**Comment by stan-dot** [comment]
I realized that sonarcloud was not visible, and the adding process as 'github app' was a bit *magic*. 

there is also an option to configure it with a github action, which is more aligned with how other similar tools are used at DLS. Investigating that setup now

**Comment by stan-dot** [comment]
https://github.com/marketplace/actions/sonarcloud-scan
