### ISSUE TITLE
Remove models that are just wrappers for lists

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#624]
DeviceResponse, PlanResponse and TaskListResponse base models all just wrap a list. We could just return the list.

**Comment by callumforrester** [comment]
See the top answer here: https://softwareengineering.stackexchange.com/questions/286293/whats-the-best-way-to-return-an-array-as-a-response-in-a-restful-api

**Comment by stan-dot** [comment]
petition to close as not planned @DiamondJoseph

**Comment by callumforrester** [comment]
I wanted to make sure this is documented in @keithralphs' service design guidelines, once I've checked I'll close this.

**Comment by stan-dot** [comment]
link for reference https://gitlab.diamond.ac.uk/sscc-docs/developer-guide/-/merge_requests/115
