### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#665]
FAILED tests/unit_tests/worker/test_task_worker.py::test_worker_and_data_events_produce_in_order - TimeoutError

**Comment by stan-dot** [comment]
from discussion with @DiamondJoseph  - a change to the test is not needed, as the error is due to the bluesky dependency change

**Comment by callumforrester** [comment]
In which case, can this be closed?

**Comment by stan-dot** [comment]
yes, closing
