### ISSUE TITLE
Plans with Optional fields of non-serialisable types (e.g. `Callable`s) should be able to be imported

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#711]
`bluesky.plans.count` has a an argument of type `PerShot` which is not serialisable. 

If we were able to ignore all fields that are optional and of a non-serialisable type, and our decorator handling was brought into blueapi import, then we could use a bare version of that plan rather than requiring wrapping it.

**Comment by callumforrester** [comment]
I think this is a duplicate of https://github.com/DiamondLightSource/blueapi/issues/652

**Comment by DiamondJoseph** [comment]
Agreed
