### ISSUE TITLE
 Tests do not complete when one fails

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#736]
When running tests on the command line, if one test fails, `pytest` immediately exits without executing the remaining tests. As a developer I often want to see a summary of which tests pass and which tests fail.

## Steps To Reproduce
1. Checkout `main`
2. Run `tox -e tests`, confirm they pass
3. Insert `raise RuntimeError` into the test of your choice 
4. Run `tox -e tests`
5. Confirm that `pytest` exits immediately on the `RuntimeError`

## Acceptance Criteria
- Pytest runs all the tests it is instructed to regardless of whether they pass or fail
- Pytest displays a summary of which tests passed and which tests failed

**Comment by callumforrester** [comment]
Thanks to @tpoliaw for spotting this.

[This update to the copier template](https://github.com/DiamondLightSource/python-copier-template/commit/67a2937511d5d6c3b9ed4f5ca9f94b602b9bbc9e#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R7) adds this behaviour if `$PYTEST_RAISE` is `1`. So the actual bug is that it happens all the time, ignoring `$PYTEST_RAISE`.

The required `if` statement was accidentally missed [when we updated the copier template](https://github.com/DiamondLightSource/blueapi/pull/717/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128).

The fix is just to add it back in.

**Comment by tpoliaw** [comment]
See also https://github.com/DiamondLightSource/mx-bluesky/pull/624. Is it worth checking other projects that use copier stuff to check they're not also affected?
