### ISSUE TITLE
 Blueapi does not call connect on all devices in a dodal beamline

### ISSUE THREAD

**Issue by DiamondJoseph** [DiamondLightSource/blueapi#746]
In dodal 1.36 and onwards, some ophyd-async devices are not connected on instantiation due to use of the new `device_factory` decorator. We need to call connect on those devices on startup, to ensure they are available in the blueapi context, can report on disconnected/errored devices and can use those devices in future plans.

## Steps To Reproduce
1. Start blueapi with the environment loading `dodal.adsim beamline` (Kind=dodal), `plan.plans` (Kind=planFunctions) from dodal
2. Run a `count` plan with `det` from that beamline module.
 
## Acceptance Criteria
- The above count plan works out of the box.

**Comment by callumforrester** [comment]
@DiamondJoseph 
Are blueapi/dodal not working as-designed here? With `@device_factory` we chose to make devices eager via `connect_immediately=True`. That is not supplied for any of the devices in the p45 module, so blueapi interprets that as an instruction to treat them as lazy

**Comment by DiamondJoseph** [comment]
connect_immediately is for the command line usecase (e.g. `det = i22.saxs(connect_immediately=True)`).

Blueapi needs to respect sim_backend and skip but always connect devices.
